/***********************************************************************/
/*                                                                     */
/*  FILE        :CameraTest.c                                          */
/*  DATE        :Sat, Oct 16, 2010                                     */
/*  DESCRIPTION :main program file.                                    */
/*  CPU GROUP   :62                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
#include "sfr62p.h"
#include "inc.h"
#include "serial.h"
#include "h-ware.h"
#include "rskM16C62Pdef.h"
#include "iic.h"


#define DATA		p0
#define Href		p1_0
#define Vsync		p1_1
#define Dclk		p1_2

#define SW_FL		p2_1
#define SW_FR		p2_3
#define SW_BL		p2_0
#define SW_BR		p2_2

#define CAM_REG_CLK 		0x11
#define CAM_REG_CONTROL_A 	0x12
#define CAM_RESET 			0x80
#define CAM_FREQ_HI 		0x08
#define CAM_FREQ_MED 		0x0e
#define CAM_REG_CONTROL_C 	0x14
#define CAM_DAT_QCIF 		0x20


/*Some prototypes*/
void grabPic(UBYTE h, UBYTE v);

UBYTE debounceFL(){
    static UWORD State = 0; // Current debounce status
    State=(State<<1) | SW_FL | 0xe000;
    if(State==0xe000)return TRUE;
    return FALSE; 
}

UBYTE debounceFR(){
    static UWORD State = 0; // Current debounce status
    State=(State<<1) | SW_FR | 0xe000;
    if(State==0xe000)return TRUE;
    return FALSE; 
}

UBYTE debounceBL(){
    static UWORD State = 0; // Current debounce status
    State=(State<<1) | SW_BL | 0xe000;
    if(State==0xe000)return TRUE;
    return FALSE; 
}

UBYTE debounceBR(){
    static UWORD State = 0; // Current debounce status
    State=(State<<1) | SW_BR | 0xe000;
    if(State==0xe000)return TRUE;
    return FALSE; 
}

extern volatile  	Fifo RxFifo;
extern volatile	Fifo TxFifo;


void main(void)
{
	UBYTE 	rxChar = 0;
	UBYTE	motCommand = 0;
	UBYTE	motSpeed = 0;	
	
	INTSOFF; /* Interrupt disable */ 
	initHW();
	initPins();
	initUART0(4);	//br115200	connected to PC		
	initUART2(2);	//br38400		connected to PIC
	initI2C();
	initADC();   
	initTimerA0();
	
	LED_PORT_DR = LEDS_ON;

	INTSON; 
	
	I2C_byte_write(CAM_REG_CONTROL_A, I2C_byte_read(CAM_REG_CONTROL_A)|0x80);
	while(1){
		//limit switches check
		if(debounceFL() == TRUE){
			tellJava(3, 10);
			UART0puts("Front-Left");	//notify java
			UART2putc(0xf4);				//tell pic to referse
			UART2putc(5);

		}
	
		if(debounceFR() == TRUE){
			tellJava(3, 11);
			UART0puts("Front-Right");	//notify java
			UART2putc(0xf4);				//tell pic to referse
			UART2putc(5);

		}
	
		if(debounceBL() == TRUE){
			tellJava(3, 9);
			UART0puts("Back-Left");	//notify java
			UART2putc(0xf3);				//tell pic to referse
			UART2putc(5);

		}
	
		if(debounceBR() == TRUE){
			tellJava(3, 10);
			UART0puts("Back-Right");	//notify java
			UART2putc(0xf3);				//tell pic to referse
			UART2putc(5);

		}		
		while(DataInFifo(&RxFifo) != 0){ 	//is there something in buffer
			rxChar = getfifo(&RxFifo);
			if(rxChar == 'c'){//CIF image request
				
				INTSOFF;
					
				UART0putc(0);
				UART0putc((0x14f80 >> 24) & 0xff);
				UART0putc((0x14f80 >> 16) & 0xff);
				UART0putc((0x14f80 >> 8) & 0xff);
				UART0putc((0x14f80 >> 0) & 0xff);
					
				//I2C_byte_write(0x03, 0x04);
			
				I2C_byte_write(CAM_REG_CLK, I2C_byte_read(CAM_REG_CLK) | CAM_FREQ_MED);	//sets low cam frequency

				grabPic(352, 244);

				I2C_byte_write(CAM_REG_CLK, I2C_byte_read(CAM_REG_CLK) | 0x00);
					
				INTSON;
			}
					
			if(rxChar == 'q'){//QCIF request
					
				INTSOFF;
					
				UART0putc(1);
				UART0putc((0x6300 >> 24) & 0xff);
				UART0putc((0x6300 >> 16) & 0xff);
				UART0putc((0x6300 >> 8) & 0xff);
				UART0putc((0x6300 >> 0) & 0xff);
					
				//I2C_byte_write(0x03, 0x04);
					
				I2C_byte_write(CAM_REG_CONTROL_C, CAM_DAT_QCIF);	//and picture format to 176x144
				
				I2C_byte_write(CAM_REG_CLK, I2C_byte_read(CAM_REG_CLK) | CAM_FREQ_HI);	//sets low cam frequency

				grabPic(176, 144);

				I2C_byte_write(CAM_REG_CLK, I2C_byte_read(CAM_REG_CLK) | 0x00);
				
				INTSON;
			}
					
			if(rxChar == 'm'){		//'m' means that commands for motor control are send
				
				tellJava(3, 9);
				UART0puts("Moving...");
				
				while(DataInFifo(&RxFifo) == 0){;}	
				motCommand = getfifo(&RxFifo);
				while(DataInFifo(&RxFifo) == 0){;}		
				motSpeed = getfifo(&RxFifo);					
						
				UART2putc(motCommand);
				UART2putc(motSpeed);		
			}
			//Resetfifo(&RxFifo);
			rxChar = 0;
		}
	}    
}

void grabPic(UBYTE hor, UBYTE ver){
	//UBYTE p;
	UWORD y, r, h;
	UWORD horizontal, vertical;
	
	
	horizontal = hor;
	vertical = ver;
	
 	for(y = 0; y < horizontal; y++){
		
	  	while(Vsync == 1);
	  	while(Vsync == 0);
	  	for(r = 0; r < vertical; r++){
			
	    		while(Href == 0);
			for(h = 0; h < y; h++){
				
			  	while(Dclk == 1);
	    	  		while(Dclk == 0);
	    		}
			UART0putc(DATA);
			while(Href == 1);
	  	}
	}
}
